### PR TITLE
Update functions.php

### PR DESCRIPTION
**Pull request by bakkan**
droped the sb functions, It's shit....  The original author is Naocan ...

### CODE REVIEW

**Comment by JingwenTian** [comment]
哈哈, 赤果果的...

**Comment by j2712482** [comment]
嘴里喊不要的人，其实都是想要的！

**Comment by j2712482** [comment]
good !!!

**Comment by JingwenTian** [comment]
cool !!!

**Comment by bakkan** [comment]
my english is very good!!!

**Comment by wangbangkun** [comment]
relax

**Comment by bakkan** [comment]
@wangbangkun relax what , do you know thinkphp is one tuo shit ?? ....

**Pull request closed without merging**
